import fs from 'fs';
const file = '/app/applet/src/data/questions.ts';
const content = fs.readFileSync(file, 'utf8');
const lines = content.split('\n');
const newContent = lines.slice(0, 247).join('\n') + `
      {no:{t:"T9: Passasjersikkerhet",q:"Hva er hensikten med drosjesjåførens plikt til ruteplanlegging og god lokalkunnskap?",o:["Å lokke flest mulig bompenger ut av kunden","Å frakte passasjeren trygt, effektivt, komfortabelt og mest mulig miljøvennlig","Å unngå motorveien for å oppleve lokal natur","Det finnes ingen slik drosjeplikt"],c:1,e:"Sjåføren skal velge mest hensiktsmessig kjørerute for å sikre en behagelig, effektiv og miljøbevisst transport for passasjeren."},en:{t:"T9: Passenger Security",q:"What is the objective of local route planning and navigational knowledge in taxi operations?",o:["Exposes customers to maximum traffic tolls","Transport passengers safely, efficiently, comfortably, and environmental-friendly","Driving around highways into scenic secondary roads","There are no regulations for routes"],c:1,e:"A proper route planning minimizes fares and maximizes safety."}},
      {no:{t:"T3: Mennesket i trafikken",q:"Hvordan påvirkes vanligvis reaksjonsevnen og sidesynet til en drosjesjåfør ved langvarig tretthet?",o:["Reaksjonstiden blir kortere (bedre)","Sidesynet snevres inn (tunnelsyn) og reaksjonstiden øker kraftig","Sidesynet blir bredere","Sidesynet forblir helt uendret"],c:1,e:"Tretthet fører to nedsatt konsentrasjon, tunnelsyn, svekket farts- og avstandsbedømmelse, og drastisk økt reaksjonstid."},en:{t:"T3: Humans in Traffic",q:"How does prolonged fatigue affect a professional taxi driver's visual field and reaction speed?",o:["Reaction speeds improve","Visual field narrows (tunnel vision) and reaction time increases significantly","Visual range expands","Fatigue doesn't change optic responses"],c:1,e:"Tiredness reduces awareness, causes tunnel vision, and slow reaction times."}},
      {no:{t:"T5: Teknisk om kjøretøyet",q:"Hva oppnår man i drosjedrift ved å kjenne bilens spesifikasjoner og kontrollere dekk og lufttrykk regelmessig?",o:["Flate dekk oftere på tur","Optimal drivstofføkonomi, riktig veigrep og minimal slitasje på dekkene","Ingen reell effekt unntatt utgifter","Høyere makshastighet på snø"],c:1,e:"Riktig lufttrykk og godkjente dekk sikrer at bilen reagerer optimalt på bremsing og styring, i tillegg til å redusere driftsutgifter."},en:{t:"T5: Vehicle Technical",q:"What are the main benefits of inspecting taxi tyre pressure and specifications?",o:["Bigger risk of flat tyres","Optimized fuel economy, correct traction grip, and minimized wear","No measurable effects except maintenance cost","Higher top speed in snowstorms"],c:1,e:"Regular tire maintenance saves fuel, guarantees braking grip, and prevents wear."}}
    ]
  },
  lastebil: {
    themes: {
      no:{"T1: Løyveplikt og markedsadgang":"#c2410c","T2: Krav til løyvehaver":"#d97706","T3: Faglig kompetanse":"#0891b2","T4: Kjøre- og hviletid":"#dc2626","T5: Fartsskriver (takograf)":"#7c3aed","T6: Kabotasje":"#059669","T7: Fraktbrev og ansvar (CMR)":"#be123c","T8: Farlig gods (ADR)":"#0d9488","T9: Vekt og dimensjoner":"#4f46e5","T10: Arbeidsmiljø og HMS":"#1a9e52"},
      en:{"T1: Licence & Market Access":"#c2410c","T2: Licence Holder Requirements":"#d97706","T3: Professional Competence":"#0891b2","T4: Driving & Rest Times":"#dc2626","T5: Tachograph":"#7c3aed","T6: Cabotage":"#059669","T7: Consignment Notes & Liability (CMR)":"#be123c","T8: Dangerous Goods (ADR)":"#0d9488","T9: Weight & Dimensions":"#4f46e5","T10: Labour Law & HSE":"#1a9e52"},
      ar:{"T1: رخصة النقل والوصول للسوق":"#c2410c","T2: متطلبات صاحب الرخصة":"#d97706","T3: الكفاءة المهنية":"#0891b2","T4: أوقات القيادة والراحة":"#dc2626","T5: جهاز التسجيل (التاكوغراف)":"#7c3aed","T6: الكابوتاج":"#059669","T7: سند الشحن والمسؤولية (CMR)":"#be123c","T8: البضائع الخطرة (ADR)":"#0d9488","T9: الأوزان والأبعاد":"#4f46e5","T10: قانون العمل والسلامة":"#1a9e52"}
    },
    q: [
      {no:{t:"T1: Løyveplikt og markedsadgang",q:"Hva gir løyve for godstransport rett til?",o:["Transportere egne varer","Drive godstransport mot vederlag med kjøretøy over 3500 kg","Kjøre tyngre lastebiler uten krav","All yrkeskjøring"],c:1,e:"Løyve for godstransport gir rett til å drive godstransport mot vederlag med motorvogn over 3500 kg."},en:{t:"T1: Licence & Market Access",q:"What does a goods transport licence authorise?",o:["Transport own goods","Carry out goods transport for reward with vehicles over 3500 kg","Drive heavier lorries without requirements","All commercial driving"],c:1,e:"A goods transport licence authorises goods transport for reward with vehicles over 3500 kg."},ar:{t:"T1: رخصة النقل والوصول للسوق",q:"ما الذي تُخوّل رخصة نقل البضائع القيام به؟",o:["نقل بضائعك الخاصة","ممارسة نقل البضائع بأجر بمركبات فوق 3500 كغ","قيادة الشاحنات الثقيلة دون شروط","جميع القيادة التجارية"],c:1,e:"تُخوّل رخصة نقل البضائع ممارسة نقل البضائع بأجر بمركبات تتجاوز 3500 كغ."}},
      {no:{t:"T2: Krav til løyvehaver",q:"Hva slags økonomisk garanti må en løyvehaver for godstransport over 3000 kg fremlegge for det første løyvet i Norge?",o:["Det kreves ingen økonomisk garanti","En bank/forsikringsgaranti med et verdi tilsvarende et fastsatt beløp (tilsvarer f.eks. 9000 euro)","Minst 10 000 kr i kontanter","Huset må være stilt i pant"],c:1,e:"Løyvehavere må dokumentere tilfredsstillende økonomisk evne gjennom en garantierklæring fra bank eller forsikringsselskap."},en:{t:"T2: Licence Holder Requirements",q:"What financial guarantee must general road haulage operators (over 3000 kg) provide for the first license in Norway?",o:["None required","A bank or insurance declaration representing a set amount (e.g., equivalent of 9000 Euros)","Cash deposit of 10,000 NOK","Personal real estate mortgage"],c:1,e:"Operators must document financial capability via financial backing guarantees from financial institutions."}},
      {no:{t:"T3: Faglig kompetanse",q:"Hvordan dokumenterer en løyvesøker for godstransport (over 3000 kg) sin faglige kompetanse?",o:["Med alminnelig førerkort klasse B eller C","Bestått særskilt nasjonal eksamen for faglig kompetanse arrangert av Statens vegvesen","Ved å ha jobbet ett år som sjåfør","Muntlig samtale med samferdselsmyndighetene"],c:1,e:"Faglig kompetanse for tyngre løyver bevises ved å ta og bestå den skriftlige, nasjonale løyveeksamenen."},en:{t:"T3: Professional Competence",q:"How must an applicant for a truck haulage licence prove their professional competence?",o:["With a regular class B or C driver's licence","Passing a dedicated national exam arranged by the Norwegian Public Roads Administration","Working one year as an apprentice","Oral interview with the transport ministry"],c:1,e:"The transport manager has to pass a written exam to certify theoretical professional competence."}},
      {no:{t:"T4: Kjøre- og hviletid",q:"Hva er den generelle daglige maksimale kjøretiden for en lastebilsjåfør etter kjøre- og hviletidsreglene?",o:["6 timer","9 timer (kan utvides til 10 timer inntil 2 ganger i uken)","12 timer","Ubegrenset så lenge man tar pauser underveis"],c:1,e:"Den daglige kjøretiden skal som hovedregel ikke overstige 9 timer. Den kan utvides til høyst 10 timer maksimalt to ganger i løpet av en uke."},en:{t:"T4: Driving & Rest Times",q:"What is the general maximum daily driving limit for a heavy truck driver, under standard regulations?",o:["6 hours","9 hours (can extend to 10 hours max twice a week)","12 hours","Unlimited with minor breaks"],c:1,e:"Daily driving hours must not exceed 9, though extensions to 10 are allowed up to twice a week."}},
      {no:{t:"T4: Kjøre- og hviletid",q:"Etter hvor lang sammenhengende kjøring må en lastebilsjåfør ta en uavbrutt pause på minst 45 minutter?",o:["Etter 3 timer","Etter 4,5 timer","Etter 6 timer","Kun ved slutten av skiftet"],c:1,e:"Etter en uavbrutt kjøreperiode på fire og en halv time (4,5t) skal føreren ta en uavbrutt pause på minst 45 minutter, med mindre han tar fulle hviletidstimer."},en:{t:"T4: Driving & Rest Times",q:"After how many consecutive driving hours must a driver take an uninterrupted break of at least 45 minutes?",o:["After 3 hours","After 4.5 hours","After 6 hours","Only at the shift end"],c:1,e:"An accumulated driving block of 4.5 hours dictates a 45-minute continuous rest break."}},
      {no:{t:"T5: Fartsskriver (takograf)",q:"Er det påbudt å registrere aktivitet manuelt på fartsskriveren (takografen) dersom du som sjåfør har utført annet arbeid utenfor bilen?",o:["Nei, det meste registreres uansett digitalt","Ja, alt annet arbeid skal registreres manuelt under symbolet for kryssede hammere","Det trengs bare hvis politiet forlanger det","Er helt valgfritt"],c:1,e:"All tid brukt til annet arbeid som lasting, lossing, rengjøring eller administrativt arbeid skal føres manuelt som annet arbeid i fartsskriveren."},en:{t:"T5: Tachograph",q:"Is it mandatory to manually input activities on the tachograph if you have completed non-driving work outside the cab?",o:["No, digital tachographs manage it automatically","Yes, all other work must be manually logged as other activities (crossed hammers symbol)","Only if police officers request it","Totally optional"],c:1,e:"Any alternative work must be registered on the driver card under the crossed hammers symbol."}},
      {no:{t:"T6: Kabotasje",q:"Hva betyr drosje- eller godskabotasje i Norge?",o:["Salg av brukte lastebiler mellom land","Transport der en utenlandsk transportør utfører innenlands transport i en annen stat (f.eks. Norge)","Spesielle tillatelser for dyretransport","Avgift på containere"],c:1,e:"Kabotasje er transportoppdrag som utføres innenlands i en annen stat enn den der transportøren hører hjemme."},en:{t:"T6: Cabotage",q:"What is cabotage in commercial goods road transport?",o:["Export-import duty on trucks","Domestic transport between points inside another country done by a foreign registered company","Special permit for trans-border shipping","Customs declaration for containers"],c:1,e:"Cabotage refers to national services inside a host country by a foreign-registered operator."}},
      {no:{t:"T7: Fraktbrev og ansvar (CMR)",q:"Hvilken konvensjon regulerer transportørens ansvar og fraktbrev ved internasjonal godstransport på vei?",o:["ADR-konvensjonen","CMR-konvensjonen","Vegtrafikkloven","Yrkestransportloven"],c:1,e:"CMR-konvensjonen danner grunnlaget for regler om fraktsedler og transportørens ansvar ved internasjonal veifrakt."},en:{t:"T7: Consignment Notes & Liability (CMR)",q:"Which international convention governs road carrier liability and logistics documentation for international goods?",o:["ADR agreement","CMR convention","Tachograph treaty","Schengen treaty"],c:1,e:"The CMR convention covers contract conditions, lost goods, liability, and consignment documents."}},
      {no:{t:"T8: Farlig gods (ADR)",q:"Hva kreves av sjåføren for å transportere gods som er klassifisert som farlig gods (ADR) over frigrensen?",o:["Ingenting ekstra, klasse C førerkort er nok","Sjåføren må inneha et gyldig ADR-kompetansebevis","Sjåføren må ha utført kjøringen i fem år","Lastebilen må ha hvit lakkfarge"],c:1,e:"Transport av farlig gods over frigrense krever et gyldig ADR-bevis som beviser gjennomført kursing og bestått eksamen."},en:{t:"T8: Dangerous Goods (ADR)",q:"What must a driver obtain to transport classified dangerous goods (ADR) above standard exemption amounts?",o:["Nothing extra, core license is adequate","A valid ADR professional competence certificate (ADR-kort)","Minimum 5 years heavy truck experience","The truck must have dedicated white bodywork"],c:1,e:"ADR transport requires a specialized safety training certificate from authorities."}},
      {no:{t:"T9: Vekt og dimensjoner",q:"Hva er den generelle tillatte maksimale bredden for tunge kjøretøy på norske veier uten spesiell dispensasjon?",o:["2,40 meter","2,55 meter (2,60 meter for visse isolerte kjøretøy)","2,75 meter","3,00 meter"],c:1,e:"Den maksimale breddebegrensningen på offentlige veier i Norge er generelt 2,55 meter, med unntak for godkjente isolerte frysekasser som kan være 2,60 meter."},en:{t:"T9: Weight & Dimensions",q:"What is the general maximum width permitted for heavy commercial vehicles on Norwegian roads?",o:["2.40 meters","2.55 meters (2.60 meters for certain temperature-controlled insulated bodies)","2.75 meters","3.00 meters"],c:1,e:"Vehicles are legally limited to 2.55m in width, with 2.60m allowed for insulated cargo containers."}},
      {no:{t:"T10: Arbeidsmiljø og HMS",q:"Hva er hovedformålet med forskriftsmessig lastsikring på en godstransportlastebil?",o:["Å gjøre lastebilen tyngre og bedre på snø","Å hindre at lasten forskyver seg, faller av, eller endrer kjøretøyets stabilitet og tyngdepunkt","Å skjule lasten fra tollen","Å unngå spenning i støtdemperne"],c:1,e:"Lastsikring skal tåle både forover, bakover og sideveis krefter for å unngå ulykker eller at lasten skaper farlig ubalanse under kjøring."},en:{t:"T10: Labour Law & HSE",q:"What is the primary objective of proper cargo securing regulations on commercial lorries?",o:["To increase truck weight for winter driving","To prevent the cargo from shifting, falling off, or disrupting vehicle stability and center of gravity","To conceal goods from checking officials","To prevent tension in the rear shocks"],c:1,e:"Cargo securing absorbs movement force, preventing dynamic destabilization and losing cargo."}}
    ]
  }
};
`;
fs.writeFileSync(file, newContent);
